const byId=id=>document.getElementById(id);const menu=byId('menu'),nav=byId('nav');if(menu)menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));if(byId('yearNow'))byId('yearNow').textContent=new Date().getFullYear();
const progress=byId('progress');addEventListener('scroll',()=>{if(progress){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?scrollY/h*100:0)+'%'}});const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -35px'});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=(i%4)*70+'ms';observer.observe(el)});
const form=byId('partForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();let g=id=>byId(id).value;let msg=`Hi Rohan Automobiles, I need a car electronic part.\n\nCar: ${g('brand')} ${g('model')}\nYear: ${g('year')||'Not specified'}\nPart: ${g('part')}\nOEM/Part No: ${g('oem')||'Not available'}\nPreference: ${g('type')}`;window.open('https://wa.me/918700599085?text='+encodeURIComponent(msg),'_blank')});
let catalog=[],visibleLimit=12;const brandEl=byId('catalogBrand'),modelEl=byId('catalogModel'),categoryEl=byId('catalogCategory'),searchEl=byId('catalogSearch'),sortEl=byId('catalogSort');
function uniq(a){return[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function setOptions(el,v,l){const c=el.value;el.innerHTML=`<option value="">${l}</option>`+v.map(x=>`<option value="${x.replace(/"/g,'&quot;')}">${x}</option>`).join('');if(v.includes(c))el.value=c}
function kindFor(p){const s=(p.category+' '+p.name).toLowerCase();if(/ecu|ecm|module|control unit/.test(s))return'ecu';if(/nox|pm sensor|differential|urea|def|exhaust|bs6|scr/.test(s))return'bs6';if(/connector|coupler|socket|wiring/.test(s))return'connector';if(/switch|lock/.test(s))return'switch';if(/actuator|throttle|valve|motor/.test(s))return'actuator';return'sensor'}
function iconFor(p){return({ecu:'▦',bs6:'⌁',connector:'⌘',switch:'⚡',actuator:'◉',sensor:'◎'})[kindFor(p)]}
function filtered(){const q=searchEl.value.trim().toLowerCase(),b=brandEl.value,m=modelEl.value,c=categoryEl.value;let items=catalog.filter(p=>{const h=[p.name,p.brand,p.category,p.oem_part_no,...(p.models||[])].filter(Boolean).join(' ').toLowerCase();return(!q||h.includes(q))&&(!b||p.brand===b)&&(!m||(p.models||[]).includes(m))&&(!c||p.category===c)});const s=sortEl?sortEl.value:'name';items.sort((x,y)=>{if(s==='brand')return(x.brand||'').localeCompare(y.brand||'')||(x.name||'').localeCompare(y.name||'');if(s==='category')return(x.category||'').localeCompare(y.category||'')||(x.name||'').localeCompare(y.name||'');return(x.name||'').localeCompare(y.name||'')});return items}
function refresh(){const b=brandEl.value,r=b?catalog.filter(p=>p.brand===b):catalog;setOptions(modelEl,uniq(r.flatMap(p=>p.models||[])),'All models');setOptions(categoryEl,uniq(r.map(p=>p.category)),'All categories')}
function wa(p){const msg=`Hi Rohan Automobiles, I want to enquire about this electronic part.\n\nPart: ${p.name}\nBrand: ${p.brand}\nModel/Application: ${(p.models||[]).join(', ')||'Please confirm'}\nCategory: ${p.category}\nOEM/Part No: ${p.oem_part_no||'Not listed'}\n\nPlease confirm availability, exact compatibility and your price.`;return'https://wa.me/918700599085?text='+encodeURIComponent(msg)}
function renderQuickCats(){const box=byId('quickCats');if(!box)return;const groups=[['','All','✦'],['Sensors','Sensors','◎'],['ECM / ECU','ECU / ECM','▦'],['ABS Sensors','ABS','◉'],['Oxygen / Lambda Sensors','Oxygen','○'],['NOx Sensors','NOx','N'],['PM Sensors','PM','P'],['Differential Pressure Sensors','DPF Pressure','⌁'],['Urea Injectors / DEF','Urea / DEF','↯']];box.innerHTML=groups.map(([v,l,i])=>`<button class="quickCat${categoryEl.value===v?' active':''}" type="button" data-cat="${v}"><span class="qcIcon">${i}</span>${l}</button>`).join('');box.querySelectorAll('.quickCat').forEach(btn=>btn.onclick=()=>{categoryEl.value=btn.dataset.cat;visibleLimit=12;renderQuickCats();render()})}
function render(){const items=filtered();byId('catalogCount').textContent=catalog.length;byId('catalogStatus').textContent=`${items.length} matching parts — availability and fitment to be confirmed.`;byId('catalogGrid').innerHTML=items.slice(0,visibleLimit).map(p=>{const k=kindFor(p);return`<article class="catalogCard" data-kind="${k}"><div class="catalogArt"><span class="catalogArtIcon">${iconFor(p)}</span><span class="catalogArtLabel">${p.category}</span></div><div class="catalogBody"><div class="catTop"><span class="chip">${p.category}</span><span class="brandChip">${p.brand}</span></div><h3>${p.name}</h3><dl>${(p.models||[]).length?`<div><dt>Models</dt><dd>${p.models.join(', ')}</dd></div>`:''}${p.oem_part_no?`<div><dt>OEM / Part No.</dt><dd>${p.oem_part_no}</dd></div>`:''}</dl><p class="verify">Confirm exact fitment & availability before ordering.</p><a class="btn" target="_blank" rel="noopener" href="${wa(p)}">Enquire on WhatsApp →</a></div></article>`}).join('')||'<div class="noResults"><b>No matching part found.</b><br><span>Try a broader search or WhatsApp us.</span></div>';byId('showMore').hidden=items.length<=visibleLimit}
if(brandEl)fetch('catalog-data.json?v=20260820c').then(r=>r.json()).then(d=>{catalog=d.products||[];setOptions(brandEl,uniq(catalog.map(p=>p.brand)),'All brands');refresh();renderQuickCats();render()}).catch(()=>{byId('catalogStatus').textContent='Catalogue could not load. Please use WhatsApp enquiry.'});if(brandEl)brandEl.onchange=()=>{visibleLimit=12;refresh();renderQuickCats();render()};[modelEl,categoryEl].filter(Boolean).forEach(e=>e.onchange=()=>{visibleLimit=12;renderQuickCats();render()});if(searchEl)searchEl.oninput=()=>{visibleLimit=12;render()};if(sortEl)sortEl.onchange=()=>{visibleLimit=12;render()};if(byId('resetFilters'))byId('resetFilters').onclick=()=>{searchEl.value='';brandEl.value='';refresh();modelEl.value='';categoryEl.value='';if(sortEl)sortEl.value='name';visibleLimit=12;renderQuickCats();render()};if(byId('showMore'))byId('showMore').onclick=()=>{visibleLimit+=12;render()};